name: Run main.py

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  run-main:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader popular

      - name: Generate stopwords file
        run: python scripts/generate_stopwords.py

      - name: Sanity check on main.py
        run: |
          python -c "import main"
      
